"""empty message

Revision ID: 7ba2099d5978
Revises: 
Create Date: 2020-04-06 22:15:05.555550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ba2099d5978'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enseignants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prenom', sa.String(length=45), nullable=False),
    sa.Column('nom', sa.String(length=45), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('confirmation', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('etudiants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prenom', sa.String(length=45), nullable=False),
    sa.Column('nom', sa.String(length=45), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('mac_address', sa.String(length=48), nullable=True),
    sa.Column('confirmation', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mac_address'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('salles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=128), nullable=True),
    sa.Column('nom_salle', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lecons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sujet', sa.String(length=45), nullable=False),
    sa.Column('enseignant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['enseignant_id'], ['enseignants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lecons_id', sa.Integer(), nullable=False),
    sa.Column('salles_id', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['lecons_id'], ['lecons.id'], ),
    sa.ForeignKeyConstraint(['salles_id'], ['salles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('absence',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('etudiant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etudiant_id'], ['etudiants.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('etudiant_id')
    )
    op.create_table('presence',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('etudiant_id', sa.Integer(), nullable=False),
    sa.Column('date_message', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['etudiant_id'], ['etudiants.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('session_id', 'etudiant_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presence')
    op.drop_table('absence')
    op.drop_table('session')
    op.drop_table('lecons')
    op.drop_table('salles')
    op.drop_table('etudiants')
    op.drop_table('enseignants')
    # ### end Alembic commands ###
