"""empty message

Revision ID: d71c98aaec82
Revises: 9d3f248e4948
Create Date: 2020-03-14 00:38:05.337609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd71c98aaec82'
down_revision = '9d3f248e4948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('user')
    op.drop_constraint('client_user_id_fkey', 'client', type_='foreignkey')
    op.create_foreign_key(None, 'client', 'user1', ['user_id'], ['id'])
    op.drop_constraint('grant_user_id_fkey', 'grant', type_='foreignkey')
    op.create_foreign_key(None, 'grant', 'user1', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('token_user_id_fkey', 'token', type_='foreignkey')
    op.create_foreign_key(None, 'token', 'user1', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token', type_='foreignkey')
    op.create_foreign_key('token_user_id_fkey', 'token', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'grant', type_='foreignkey')
    op.create_foreign_key('grant_user_id_fkey', 'grant', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.create_foreign_key('client_user_id_fkey', 'client', 'user', ['user_id'], ['id'])
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('image_file', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key'),
    sa.UniqueConstraint('username', name='user_username_key')
    )
    op.drop_table('user1')
    # ### end Alembic commands ###
